/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    KipuBank: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "_bankCap",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "contractBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "userBank",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "KipuBank_DepositSuccessful",
          inputs: [
            {
              name: "_amount",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "KipuBank_WithdrawSuccessful",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "KipuBank_AmountExceedsBankCap",
          inputs: [
            {
              name: "_bankCap",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_valueExceeds",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "KipuBank_AmountExceedsUserBalance",
          inputs: [
            {
              name: "_valueExceeds",
              type: "string",
              internalType: "string",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_currentUserBalanceExceeds",
              type: "string",
              internalType: "string",
            },
            {
              name: "_userBalance",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "KipuBank_AmountExceedsWithdrawLimit",
          inputs: [],
        },
        {
          type: "error",
          name: "KipuBank_TransferFailed",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1743693996.json",
      deploymentScript: "Deploy.s.sol",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
